# Generated by Django 4.2.4 on 2023-08-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_alter_program_requirements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
